# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/order_management_db1
spring.datasource.username=root
spring.datasource.password=PA23@kdpas
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.mvc.format.date=yyyy-MM-dd
# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Port
server.port=8081